### ISSUE TITLE
Smoke Test Failing

### ISSUE THREAD

**Issue by e-e-e** [e-e-e/bookcovers#24]
It looks like the smoke test is failing for amazing. The test still succeeds locally, so this is probably an issue with Amazon blocking Github actions IP. Not sure how to fix this if that is the case. But first thing first is to confirm.

**Comment by raineorshine** [comment]
✓ Tests succeed locally for me too

**Comment by e-e-e** [comment]
This has been fixed by - https://github.com/e-e-e/bookcovers/pull/26
