### ISSUE TITLE
Puppeteer Error in React App

### ISSUE THREAD

**Issue by catmclough** [e-e-e/bookcovers#4]
Attempted to use this library in a React app but I get this error in the browser:

```
./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in '.../node_modules/puppeteer/lib'
```

**Comment by e-e-e** [comment]
Yeah - perhaps the readme should be more explicit - but the library is not intended to work in the browser. Amazons CORS settings prohibits this.

**Comment by e-e-e** [comment]
I am closing this but opening a new issue for improved documentation here: https://github.com/e-e-e/book-covers-api/issues/9
